steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/prasadrpm/e-auction-gateway.git']
  
#Gradle build  
- name: 'gradle:7.5.0-jdk17'
  entrypoint: 'gradle'
  args: ['assemble']
   
#Docker Image   
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/credible-bay-346209/e-auction-gateway','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/credible-bay-346209/e-auction-gateway']
